# Flusim Web Interface Application
# Developed by Reilly Evans

# Imports
import logging
import os
import zipfile
from datetime import datetime

from fastapi import BackgroundTasks, FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse

from serverFiles.ModelSchema import modelGuideFile
from serverFiles.simulationFunctions import (  # simLocation,
    asir,
    displayTime,
    epidemic,
    generateToolboxConfig,
    runSimulation,
)

# Ensure Flusim imports work properly when called outside of toolbox
# TODO: Uncomment if AnalysisStat is used in the main function
# sys.path.append(os.path.join(os.getcwd(), simLocation, "src/toolbox"))
# from analysis.AnalysisStat import AnalysisStat

# Logging config (create log folder outside of project dir to avoid
# watchfiles getting into an endless update loop)
os.makedirs("../Logs", exist_ok=True)
logging.basicConfig(
    filename="../Logs/serverAppLogs.txt",
    filemode="a",
    format="%(asctime)s,%(msecs)03d %(name)s %(levelname)s %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    level=logging.WARN,
)


# Set this to False to preserve files after running sim
deleteFiles = True

# Throw error if Flusim files aren't present
if not os.path.isfile("src/toolbox/toolbox.py"):
    raise FileNotFoundError(
        (
            "Flusim files not found. Ensure that this application is "
            "present in the same directory as the Flusim simulation files."
        )
    )


def clearFiles(files: list[str]):
    """
    Function to remove files generated by a simulation run after it is complete

    Parameters:
        files (list of str): A list of paths to files that must be removed.
    """
    print("[clearFiles] Deleting the following files for cleanup purposes:")
    for f in files:
        print("   ", f)
    for f in files:
        os.remove(f)


# Define main Flusim app
flusimApp = FastAPI()

# CORS Middleware for ensuring only the web application can make requests
flusimApp.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # replace with production URLs
    allow_credentials=True,
    allow_methods=["POST"],
    allow_headers=["*"],
)


# Define route for receiving model parameters
@flusimApp.post("/runModel")
async def runModel(config: modelGuideFile, cleanup: BackgroundTasks):
    """
    Async route function to run a simulation experiment based on parameters
    from the dashboard, then return the analysed statistics

    Parameters:
        config (modelGuideFile): The parameters and other settings that
            will define the simulation experiment.

        cleanup (BackgroundTasks): An object that will have file removal
            functions attached to it to remove excess files once this
            function finishes running.

    Returns:
        FileResponse: The analysis CSV files generated from the simulation
            output, compressed into a single zip file.
    """
    overallStartTime = datetime.now()
    # Get relevant attributes from config file
    sessionID = config.description
    community = config.community_used[0]
    middleJoint = config.middle_joint
    # simCount = len(config.simulation_sets[0].simulations)
    print(f"Simulation received; name = {config.name}, ID = {sessionID}")

    # Generate toolbox config file
    toolboxPath = generateToolboxConfig(sessionID, middleJoint)
    print(f"Toolbox file located at {toolboxPath}")

    # Run the Flusim simulation
    simFiles = runSimulation(config, toolboxPath)

    returnFiles = []
    # TODO: Use middle joint to determine analyses to run
    middleCheck = """if middleJoint:
        # Epidemic tool
        if 'usingEpidemic' in middleJoint:
            sumStat = (
                AnalysisStat.MEAN if 'EMean' in middleJoint
                else AnalysisStat.MEDIAN
            )
            epiCumulative = 'ECumulative' in middleJoint
            epiAge = 'EAgeBased' in middleJoint
            returnFiles.append(epidemic(
                community, middleJoint, sessionID, summaryStat = sumStat,
                cumulative = epiCumulative, byAge = epiAge,
                toolboxPath = toolboxPath
            ))
        # Asir tool
        if 'usingAsir' in middleJoint:
            sumStat = (
                AnalysisStat.MEAN if 'AMean' in middleJoint
                else AnalysisStat.MEDIAN
            )
            asirProportion = 'AProportion' in middleJoint
            asirIndigenous = 'AIndigenous' in middleJoint
            asirPregnant = 'APregnant' in middleJoint
            asirVaccinated = 'AVaccinated' in middleJoint
            returnFiles.append(asir(
                community, middleJoint, sessionID,
                summaryStat = sumStat, getProportion = asirProportion,
                onlyIndigenous = asirIndigenous, onlyPregnant = asirPregnant,
                onlyVaccinated = asirVaccinated, toolboxPath = toolboxPath
            ))"""
    # for now, just get the standard analyses the dashboard uses

    # Daily infection epidemic curve
    returnFiles.append(
        epidemic(
            community, middleJoint, sessionID, cumulative=True, toolboxPath=toolboxPath
        )
    )
    # Cumulative infection epidemic curve
    returnFiles.append(
        epidemic(
            community,
            middleJoint,
            sessionID,
            cumulative=False,
            toolboxPath=toolboxPath,
        )
    )
    # Age-separated infection rates
    returnFiles.append(asir(community, middleJoint, sessionID, toolboxPath=toolboxPath))

    # Vaccinated age-separated infection rates
    if middleJoint and "+vaccine" in middleJoint:
        returnFiles.append(
            asir(
                community,
                middleJoint,
                sessionID,
                onlyVaccinated=True,
                toolboxPath=toolboxPath,
            )
        )
    # If all else fails and no analyses were specified, run epidemic
    if not returnFiles:
        print("No analyses specified; defaulting to epidemic")
        returnFiles.append(
            epidemic(community, middleJoint, sessionID, toolboxPath=toolboxPath)
        )

    print("\nAnalysis files:")
    for file in returnFiles:
        print("   ", file)

    # Zip together the analysis files if necessary
    if len(returnFiles) != 1:
        zipPath = f"serverFiles/{sessionID}_analysis.zip"
        with zipfile.ZipFile(zipPath, mode="w") as analysis:
            for file in returnFiles:
                analysis.write(file)
        returnFiles.append(zipPath)
        finalPath = zipPath
    # Just return lone CSV if only one analysis needed
    else:
        finalPath = returnFiles[0]

    # Schedule files created here to be removed
    if deleteFiles:
        cleanup.add_task(clearFiles, simFiles + returnFiles + [toolboxPath])

    print(
        f"\nSimulation request for session {sessionID} complete in "
        f"{displayTime(overallStartTime)}, returning data\n\n\n"
    )
    return FileResponse(finalPath)
