# Flusim Web Interface Application
# Developed by Reilly Evans

# Imports
import asyncio
import logging
import os
import uuid
import zipfile
from datetime import datetime

from fastapi import BackgroundTasks, FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse

from serverFiles.ModelSchema import modelGuideFile
from serverFiles.simulationFunctions import (
    activeClients,
    asir,
    completedSimulations,
    displayTime,
    epidemic,
    generateToolboxConfig,
    runSimulation,
    simulationStatus,
    simulationFiles,
    updateStatus,
)

# Ensure Flusim imports work properly when called outside of toolbox
# TODO: Uncomment if AnalysisStat is used in the main function
# sys.path.append(os.path.join(os.getcwd(), simLocation, "src/toolbox"))
# from analysis.AnalysisStat import AnalysisStat

# Logging config
os.makedirs("tempFiles", exist_ok=True)
logging.basicConfig(
    filename="tempFiles/serverAppLogs.txt",
    filemode="a",
    format="%(asctime)s,%(msecs)03d %(name)s %(levelname)s %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    level=logging.DEBUG,
)

# Throw error if Flusim files aren't present
# TODO: Check for the simulator and not just the toolbox
# (protect against running without building the executable first)
if not os.path.isfile("src/toolbox/toolbox.py"):
    raise FileNotFoundError(
        (
            "Flusim files not found. Ensure that this application is "
            "present in the same directory as the Flusim simulation files."
        )
    )


# Define main Flusim app and dictionary for
flusimApp = FastAPI()

# CORS Middleware for ensuring only the web application can make requests
flusimApp.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # replace with production URLs
    allow_credentials=True,
    allow_methods=["POST"],
    allow_headers=["*"],
)

# Set this to False to preserve files after running sim
deleteFiles = True


def clearFiles(files: set[str]):
    """
    Function to remove files generated by a simulation run after it is complete

    Parameters:
        files (set of str): A list of paths to files that must be removed.
    """
    # TODO: Add short delay if necessary for file downloads
    # TODO: Make sure files are deleted some time after a websocket breaks
    print("[clearFiles] Deleting the following files for cleanup purposes:")
    for f in files:
        print("   ", f, end="")
        try:
            os.remove(f)
            print()
        except FileNotFoundError:
            # Note files that already didn't exist
            print(" (not found)")


async def runModel(simulationID: str, config: modelGuideFile):
    """
    Async function to run a simulation experiment based on parameters
    from the dashboard, then zip the analysed statistics.

    Parameters:
        simulationID (str): The ID distinguishing this simulation task.

        config (modelGuideFile): The parameters and other settings that
            will define the simulation experiment.
    """
    try:
        # Wait 1 second for the websocket to connect
        await asyncio.sleep(1)
        overallStartTime = datetime.now()

        # Get relevant attributes from config file
        # TODO: See if fileID can be replaced with simulationID
        fileID = config.description
        community = config.community_used[0]
        middleJoint = config.middle_joint
        print(f"Simulation received; name = {config.name}, ID = {simulationID}")

        # Log the files that will be created over the course of the simulation
        simulationFiles[simulationID] = set()
        analysisFiles = []

        # Generate toolbox config file
        await updateStatus(simulationID, "generatingConfig")
        toolboxPath = generateToolboxConfig(simulationID, fileID, middleJoint)
        print(f"Toolbox file located at {toolboxPath}")

        # Run the Flusim simulation
        await runSimulation(simulationID, fileID, config, toolboxPath)

        # TODO: Use middle joint to determine analyses to run
        # (or find a way to send the data forms to the server directly)

        # for now, just get the standard analyses the dashboard uses

        # Daily infection epidemic curve
        await updateStatus(simulationID, "toolboxAnalysis0")
        analysisFiles += await asyncio.to_thread(
            epidemic,
            simulationID,
            fileID,
            community,
            middleJoint,
            cumulative=True,
            toolboxPath=toolboxPath,
        )

        # Cumulative infection epidemic curve
        await updateStatus(simulationID, "toolboxAnalysis1")
        analysisFiles += await asyncio.to_thread(
            epidemic,
            simulationID,
            fileID,
            community,
            middleJoint,
            cumulative=False,
            toolboxPath=toolboxPath,
        )

        # Age-separated infection rates
        await updateStatus(simulationID, "toolboxAnalysis2")
        analysisFiles += await asyncio.to_thread(
            asir,
            simulationID,
            fileID,
            community,
            middleJoint,
            toolboxPath=toolboxPath,
        )

        # Vaccinated age-separated infection rates
        if middleJoint and "+vaccine" in middleJoint:
            await updateStatus(simulationID, "toolboxAnalysis3")
            analysisFiles += await asyncio.to_thread(
                asir,
                simulationID,
                fileID,
                community,
                middleJoint,
                onlyVaccinated=True,
                toolboxPath=toolboxPath,
            )

        # If all else fails and no analyses were specified, run epidemic
        if not analysisFiles:
            print("No analyses specified; defaulting to epidemic")
            analysisFiles += await asyncio.to_thread(
                epidemic,
                simulationID,
                fileID,
                community,
                middleJoint,
                toolboxPath=toolboxPath,
            )

        print("\nAnalysis files:")
        for file in analysisFiles:
            print("   ", file)

        # Zip together the analysis files if necessary
        # TODO: See if simplifying to always return zip is OK
        await updateStatus(simulationID, "zippingAnalysis")
        if len(analysisFiles) != 1:
            zipPath = f"tempFiles/{fileID}_analysis.zip"
            simulationFiles[simulationID].add(zipPath)
            with zipfile.ZipFile(zipPath, mode="w") as analysis:
                for file in analysisFiles:
                    analysis.write(file)
            simulationFiles[simulationID].add(zipPath)
            finalPath = zipPath
        # Just return lone CSV if only one analysis needed
        else:
            (finalPath,) = analysisFiles

        completedSimulations[simulationID] = finalPath

        print(
            f"\nSimulation request for session {fileID} complete in "
            f"{displayTime(overallStartTime)}, ready to return data\n"
        )

        await updateStatus(simulationID, "completed")
    except Exception as e:
        # TODO: Add more info to errors like this
        await updateStatus(simulationID, "error")
        print(f"Error while running simulation {simulationID}:\n{e}")


@flusimApp.post("/runModel")
async def runModelRoute(config: modelGuideFile) -> dict[str, str]:
    """
    Async route function to begin a simulation experiment and give the
    dashboard an ID to poll for status updates.

    Parameters:
        config (modelGuideFile): The parameters and other settings that
            will define the simulation experiment.

    Returns:
        dict: A dictionary containing the ID assigned to this particular
            simulation run. A dictionary is used rather than returning the ID
            directly as an int to ensure corrupted data is not read by the
            dashboard client.
    """
    simulationID = str(uuid.uuid4())

    asyncio.create_task(runModel(simulationID, config))

    return {"simulationID": simulationID}


@flusimApp.websocket("/runModel/status/{simulationID}")
async def statusWebSocket(websocket: WebSocket, simulationID: str):
    """
    Websocket route to deliver simulation status updates live

    Parameters:
        websocket (WebSocket): The websocket to send updates to.

        simulationID (str): The ID distinguishing this simulation task.
    """
    await websocket.accept()
    if simulationID not in activeClients:
        activeClients[simulationID] = []
    activeClients[simulationID].append(websocket)

    try:
        # Send current status
        if simulationID in simulationStatus:
            await websocket.send_json({"status": simulationStatus[simulationID]})

        # Keep connection open to send updates
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        if simulationID in activeClients:
            activeClients[simulationID].remove(websocket)
            if not activeClients[simulationID]:
                del activeClients[simulationID]


@flusimApp.get("/runModel/download/{simulationID}")
async def downloadSimulationResults(simulationID: str, cleanup: BackgroundTasks):
    """
    Async route function to obtain the results of a simulation experiment.

    Parameters:
        simulationID (str): The ID distinguishing this simulation task.

        cleanup (BackgroundTasks): An object that will have file removal
            functions attached to it to remove excess files once this
            function finishes running.
    """
    if simulationID not in simulationStatus:
        return {"error": "Task not found"}

    currentStatus = simulationStatus[simulationID]
    if currentStatus != "completed":
        return {"error": "Task not completed", "status": currentStatus}

    filePath = completedSimulations.get(simulationID)

    if not filePath or not os.path.exists(filePath):
        return {"error": "File not found"}

    # TODO: Allow preserving these files until the client is disconnected
    if deleteFiles:
        cleanup.add_task(clearFiles, simulationFiles.get(simulationID, {}))

    # TODO: Remove the dictionary entries once finished

    return FileResponse(filePath, filename=os.path.basename(filePath))
