# Flusim Web Interface Application
# Developed by Reilly Evans
# Constants, classes and functions used throughout the server's operations

# Imports
import asyncio
import logging
import os
import sys
from asyncio import Task
from datetime import datetime
from subprocess import Popen
from typing import Any

from fastapi import WebSocket

# Logging
sharedLog = logging.getLogger(__name__)

# Constants

# Set this to False to preserve files after running sim
deleteGeneratedFiles = True

# Change these if file location relative to Flusim changes
simLocation = ""
executableLocation = "src/simulator/build/src/simulator"
toolboxLocation = "src/toolbox/toolbox.py"

# Ensure Flusim imports work properly when called outside of toolbox
sys.path.append(
    os.path.join(os.getcwd(), simLocation, os.path.dirname(toolboxLocation))
)


class TaskData:
    """
    Class for information regarding a server task
    """

    def __init__(self, taskID):
        self._taskID = taskID
        self._websockets = []
        self._tasks = set()
        self._process = None
        self._status = "start"
        self._files = set()
        self._results = None

    @property
    def taskID(self):
        """ID associated with this simulation"""
        return self._taskID

    @property
    def websockets(self):
        """Websockets tied to the client that requested this simulation"""
        # TODO: Does this need to be a list? 1 websocket per sim is normal
        return self._websockets

    @websockets.setter
    def websockets(self, value: list[WebSocket]):
        self._websockets = value

    @websockets.deleter
    def websockets(self):
        # TODO: Should websockets be closed in this case?
        del self._websockets

    @property
    def tasks(self):
        """Set of asyncio tasks that relate to this simulation"""
        return self._tasks

    @tasks.setter
    def tasks(self, value: set[Task]):
        self._tasks = value

    @property
    def process(self):
        """C++ subprocess currently running for this simulation"""
        return self._process

    @process.setter
    def process(self, value: Popen):
        self._process = value

    @process.deleter
    def process(self):
        if self._process is not None:
            self._process.terminate()
        del self._process

    @property
    def status(self):
        """String indicating the simulation's current progress"""
        return self._status

    @status.setter
    def status(self, value: str):
        self._status = value

    @property
    def files(self):
        """Set of file paths for files that will be created for this simulation"""
        return self._files

    @files.setter
    def files(self, value: set[str]):
        self._files = value

    @property
    def results(self):
        """Either the results to be returned, or the path to the returned file"""
        return self._results

    @results.setter
    def results(self, value: Any):
        self._results = value

    async def stopTasks(self):
        """Stop any currently running tasks for this simulation"""

        for task in self.tasks:
            # Naming tasks for logging would require Python 3.12
            task.cancel()

        # Wait for all tasks to finish cancelling
        if self.tasks:
            await asyncio.gather(*self.tasks, return_exceptions=True)


# Dict to store active tasks
activeTasks: dict[str, TaskData] = dict()


def clearFiles(files: set[str]):
    """
    Function to remove files generated by a simulation run after it is complete

    Parameters:
        files (set of str): A list of paths to files that must be removed.
    """
    # TODO: See if tempfile can replace this workaround
    # TODO: Make sure files are deleted some time after a websocket breaks
    print("[clearFiles] Deleting the following files for cleanup purposes:")
    for f in files:
        print("   ", f, end="")
        try:
            os.remove(f)
            print()
        except FileNotFoundError:
            # Note files that already didn't exist
            print(" (not found)")


async def updateStatus(sim: TaskData, state: str):
    """
    Simple async function to update the returned status of a server operation.

    Parameters:
        sim (TaskData): The object containing the data used for this simulation.

        state (str): The state to set the task to.
    """
    # TODO: If other tasks don't use TaskData modify the parameters here
    sim.status = state

    # Broadcast to connected WebSockets
    message = {"status": state}
    if not sim.websockets:
        sharedLog.warning(
            f"Task {sim.taskID} had no websockets it could update to {message}\n"
        )
    for websocket in sim.websockets:
        try:
            await websocket.send_json(message)
            sharedLog.info(f"Status for {sim.taskID} updated to {message}\n")
        except Exception as e:
            sharedLog.error(f"""
Status for {sim.taskID} wasn't updated to {message} due to the following error:
{e}\n
            """)


def displayTime(startTime: datetime) -> str:
    """
    Calculates the time since a given point and displays it in mm:ss format

    Parameters:
        startTime (datetime): The point in time to measure from.

    Returns:
        str: The time between startTime and now, as a string in mm:ss format.
    """
    endTime = datetime.now()
    totalTime = endTime - startTime
    seconds = str(totalTime.seconds % 60).zfill(2)
    return f"{totalTime.seconds // 60}:{seconds}"
