# Flusim Web Interface Application
# Developed by Reilly Evans
# Functions for running the Flusim simulation

# Imports
import json
import logging
import os
import sys
from argparse import Namespace
from datetime import datetime
from typing import Optional

import pandas as pd

from ServerFiles.ModelSchema import modelGuideFile
from ServerFiles.SharedResources import (
    TaskData,
    displayTime,
    simLocation,
    toolboxLocation,
)

# Logging
functionLog = logging.getLogger(__name__)

# Ensure Flusim imports work properly when called outside of toolbox
sys.path.append(
    os.path.join(os.getcwd(), simLocation, os.path.dirname(toolboxLocation))
)

from analysis.AnalysisStat import AnalysisStat
from logger import LogLevel
from ToolboxConfiguration import ToolboxConfiguration


# TODO: Make everything take ToolboxConfiguration directly instead of loading the path
def generateToolboxConfig(
    sim: TaskData, fileID: Optional[str], joint: Optional[str]
) -> str:
    """
    Function to generate the required toolbox config file for a simulation experiment

    Parameters:
        sim (TaskData): The object containing the data used for this simulation.

        fileID (str): The numeric identifier for the files generated for this
            simulation, stored as a string.

        joint (str): A string used to label files generated by the simulation.

    Returns:
        str: The file path for the newly created configuration file.
    """
    toolboxConfigSettings = {
        "simulator_executable": "src/simulator/build/src/simulator",
        "baseline_file": "conf/simulation.baseline.json",
        "middle_joint": joint,
        "set_id_joint": "-",
        "event_suffix": ".sqlite",
        "input_directory": "results/",
        "output_directory": "post-analysis",
        "communities": [
            {"name": "newcastle", "path": "communities/newcastle2011"},
            {"name": "cairns", "path": "communities/cairns2011"},
            {"name": "integration", "path": "integration/community"},
        ],
    }

    # Log filename preemptively in case of cancellation
    toolboxConfigPath = f"tempFiles/toolbox_config_{fileID}.json"
    sim.files.add(toolboxConfigPath)
    print(
        (
            "[generateToolboxConfig] Generating toolbox "
            f"configuration file {toolboxConfigPath}"
        )
    )
    with open(toolboxConfigPath, "w") as file:
        json.dump(toolboxConfigSettings, file, indent=2)
    return toolboxConfigPath


async def runSimulation(
    sim: TaskData,
    fileID: Optional[str],
    configData: modelGuideFile,
    toolboxPath: str,
):
    """
    Function to run a simulation experiment using the given config files

    Parameters:
        sim (TaskData): The object containing the data used for this simulation.

        fileID (str): The numeric identifier for the files generated for this
            simulation, stored as a string.

        configData (modelGuideFile): The parameters and other settings that
            will define the simulation experiment.

        toolboxPath (str): The path to the file containing settings for the
            toolbox commands.
    """
    # from commands.Run.RunCommand import RunCommand
    from ServerFiles.ToolboxOverrides import RunCommandWithData

    runStartTime = datetime.now()
    toolboxConfig = ToolboxConfiguration(toolboxPath)

    guidePath = f"tempFiles/flusim-{fileID}.guide.json"

    # Get list of sim files so they can be deleted once the
    # simulation and analysis are complete
    simFiles = {
        os.path.join(
            simLocation,
            "results",
            (
                (
                    f"{configData.community_used[0]}{configData.middle_joint}"
                    f"{configData.simulation_sets[0].version}-{i:02}.sqlite"
                )
            ),
        )
        for i in range(len(configData.simulation_sets[0].simulations))
    }

    # Log files preemptively in case of cancellation
    sim.files |= simFiles | {guidePath}

    with open(guidePath, "w") as file:
        file.write(configData.model_dump_json(indent=2, exclude_unset=True))

    # Run the simulation
    await RunCommandWithData(sim=sim).run_command_async(
        Namespace(guide=guidePath, log_level=LogLevel.DEBUG), toolboxConfig
    )
    print(
        "[runSimulation] Finished running the simulation experiment "
        f"in {displayTime(runStartTime)}\n"
    )


def epidemicFileName(options: Namespace, config: ToolboxConfiguration) -> str:
    """
    Function to construct the proper file name for epidemic results

    Parameters:
        options: The arguments for the epidemic command.

        config: The configuration settings for this simulation.

    Returns:
        str: The name of the generated file.
    """
    filename = ""

    if len(options.community) > 0:
        filename += ",".join(options.community)
    filename += config.middle_joint
    if len(options.set) > 0:
        filename += ",".join([str(s) for s in options.set])
    if len(options.filenames) > 0:
        filename += "+others"
    filename += "-epidemic-"

    if options.cumulative_sum:
        filename += "cumulative-"
    filename += f"{options.calculate_stat}"

    if not options.scale == 1.0:
        filename += f"-scale_{options.scale:.5g}"
    if options.age_adjusted is not None:
        filename += "-age_adjusted"
    if options.by_strain:
        filename += "-by_strain"
    if options.by_age:
        filename += "-by_age"
    if options.by_vaccine:
        filename += "-by_vaccine"

    return filename + ".csv"


def epidemic(
    sim: TaskData,
    fileID: Optional[str],
    communityName: str,
    summaryStat=None,
    cumulative=False,
    byAge=False,
    toolboxPath: Optional[str] = None,
) -> list[str]:
    """
    Wrapper to run the epidemic toolbox command on a given simulation output,
    generating epidemic curves in CSV format

    Parameters:
        sim (TaskData): The object containing the data used for this simulation.

        fileID (str): The numeric identifier for the files generated for this
            simulation, stored as a string.

        communityName (str): The name of the community being simulated (e.g. Newcastle).

        summaryStat (AnalysisStat, optional): Which summary statistic to use when
            generating the analysis data. Defaults to Median; None is converted
            to Median for import formatting purposes

        cumulative (bool): Set to True if you want to generate cumulative
            infections over time instead of daily infections.

        byAge (bool): Set to True if you want to generate separate epidemic
            curves for each age group.

        toolboxPath (str, optional): The path to the file containing settings
            for the toolbox commands.

    Returns:
        list of str: The name of the CSV files containing the generated
            epidemic curve(s), wrapped in a list to avoid issues when
            listing the required files.
    """
    from commands.epidemic import EpidemicCurveCommand

    epidemicStartTime = datetime.now()
    if summaryStat is None:
        summaryStat = AnalysisStat.MEDIAN
    validPath = (
        toolboxPath if toolboxPath else f"tempFiles/toolbox_config_{fileID}.json"
    )
    toolboxConfig = ToolboxConfiguration(validPath)

    # Run epidemic analysis
    # TODO: Integrate other options as params if needed by the dashboard
    epidemicArgs = Namespace(
        community=[communityName],
        set=[fileID],
        calculate_stat=summaryStat,
        cumulative_sum=cumulative,
        by_age=byAge,
        moving_average_window=7,
        scale=1,
        by_strain=False,
        by_vaccine=False,
        age_adjusted=None,
        split_output=False,
        filenames=[],
        log_level=LogLevel.DEBUG,
    )
    print(
        "[epidemic] Running 'epidemic' analysis for "
        f"set {fileID} on community {communityName}"
    )
    print(
        f"Options: [{summaryStat}]",
        "[cumulative]" if cumulative else "[individual]",
        "[age-separated]" if byAge else "[age-combined]",
    )
    # Log files preemptively in case of cancellation
    filename = os.path.join(
        simLocation, "post-analysis", epidemicFileName(epidemicArgs, toolboxConfig)
    )
    sim.files |= {filename}

    # TODO: More fine-grain progress for epidemic
    EpidemicCurveCommand().run_command(epidemicArgs, toolboxConfig)

    # Sort file and fill null values
    orderedEpidemic = (
        pd.read_csv(filename, header=0).sort_index(axis=1).set_index("day")
    )
    if cumulative:
        orderedEpidemic = orderedEpidemic.ffill()
    orderedEpidemic.to_csv(filename, na_rep="0.0")
    print(
        "[epidemic] Finished running epidemic analysis "
        f"in {displayTime(epidemicStartTime)}\n"
    )
    return [filename]


# Function for asir toolbox function
def asir(
    sim: TaskData,
    fileID: Optional[str],
    communityName: str,
    joint: Optional[str],
    summaryStat=None,
    getProportion=False,
    onlyIndigenous=False,
    onlyPregnant=False,
    onlyVaccinated=False,
    toolboxPath: Optional[str] = None,
) -> list[str]:
    """
    Wrapper to run the asir toolbox command on a given simulation output,
    generating age-separated infection rates in CSV format.

    Parameters:
        sim (TaskData): The object containing the data used for this simulation.

        fileID (str): The numeric identifier for the files generated for this
            simulation, stored as a string.

        communityName (str): The name of the community being simulated (e.g. Newcastle).

        joint (str): A string used to label files generated by the simulation.

        summaryStat (AnalysisStat, optional): Which summary statistic to use when
            generating the analysis data. Defaults to Median; None is converted
            to Median for import formatting purposes

        getProportion (bool): Set to True if you want to generate infection
            rates as proportions of the population rather than exact values.

        onlyIndigenous (bool): Set to True if you want to generate rates for
            indigenous people specifically.

        onlyPregnant (bool): Set to True if you want to generate rates for
            pregnant people specifically.

        onlyVaccinated (bool): Set to True if you want to generate rates for
            vaccinated people specifically.

        toolboxPath (str, optional): The path to the file containing settings
            for the toolbox commands.

    Returns:
        list of str: The name of the CSV file containing the generated rates,
            wrapped in a list to avoid issues when listing the required files.
    """
    from commands.ASIRAnalysis import AsirCommand

    asirStartTime = datetime.now()
    if summaryStat is None:
        summaryStat = AnalysisStat.MEDIAN
    validPath = (
        toolboxPath if toolboxPath else f"tempFiles/toolbox_config_{fileID}.json"
    )
    toolboxConfig = ToolboxConfiguration(validPath)

    # Log files preemptively in case of cancellation
    fileStem = f"{communityName}{joint}{fileID}-asir-{summaryStat}"
    oldFilename = os.path.join(simLocation, "post-analysis", f"{fileStem}.csv")
    newFilename = os.path.join(
        simLocation,
        "post-analysis",
        f"{fileStem}{'-proportion' if getProportion else '-discrete'}"
        f"{'-indigenousOnly' if onlyIndigenous else '-allDemographics'}"
        f"{'-pregnantOnly' if onlyPregnant else '-allPregnancy'}"
        f"{'-vaccinatedOnly' if onlyVaccinated else '-allVaccination'}.csv",
    )
    sim.files |= {oldFilename, newFilename}

    # Run epidemic analysis
    asirArgs = Namespace(
        community=[communityName],
        set=[fileID],
        calculate_stat=summaryStat,
        proportion=getProportion,
        indigenous=onlyIndigenous,
        pregnant=onlyPregnant,
        vaccinated=onlyVaccinated,
        filenames=[],
        log_level=LogLevel.DEBUG,
    )
    print(
        f"[asir] Running 'asir' analysis for set {fileID} on community {communityName}"
    )
    print(
        f"Options: [{summaryStat}]",
        "[proportionate]" if getProportion else "[discrete]",
        "[indigenous only]" if onlyIndigenous else "[all demographics]",
        "[pregnant only]" if onlyPregnant else "[all pregnant status]",
        "[vaccinated only]" if onlyVaccinated else "[all vaccine status]",
    )
    # TODO: More fine-grain progress for asir
    AsirCommand().run_command(asirArgs, toolboxConfig)

    # Rename file to account for all options and avoid overwriting previous data
    # TODO: Just modify the toolbox to include all parameters in the name
    os.rename(oldFilename, newFilename)

    # Order the scenarios correctly
    orderedAsir = pd.read_csv(newFilename, header=0, index_col=0).sort_index()
    orderedAsir.to_csv(newFilename, na_rep="0.0")

    print(f"[asir] Finished running asir analysis in {displayTime(asirStartTime)}\n")
    return [newFilename]
