# Flusim Web Interface Application
# Developed by Reilly Evans
# Functions for running the Flusim simulation

# Imports
import asyncio
import json
import logging
import os
import sys
from argparse import Namespace
from asyncio import Task
from datetime import datetime
from typing import Optional

import pandas as pd
from fastapi import WebSocket

from serverFiles.ModelSchema import modelGuideFile

# Change this if file location relative to Flusim changes
simLocation = ""

# Ensure Flusim imports work properly when called outside of toolbox
sys.path.append(os.path.join(os.getcwd(), simLocation, "src/toolbox"))

# Logging
functionLog = logging.getLogger(__name__)

# Set this to False to preserve files after running sim
deleteFiles = True


class SimData:
    """
    Class for information regarding a simulation
    """

    def __init__(self, simulationID: str):
        self._simulationID = simulationID
        self._websockets = []
        self._tasks = set()
        self._status = "start"
        self._files = set()
        self._results = None

    @property
    def simulationID(self):
        """ID associated with this simulation"""
        return self._simulationID

    @property
    def websockets(self):
        """Websockets tied to the client that requested this simulation"""
        return self._websockets

    @websockets.setter
    def websockets(self, value: list[WebSocket]):
        self._websockets = value

    @websockets.deleter
    def websockets(self):
        del self._websockets

    @property
    def tasks(self):
        """Set of asyncio tasks that relate to this simulation"""
        return self._tasks

    @tasks.setter
    def tasks(self, value: set[Task]):
        self._tasks = value

    @property
    def status(self):
        """String indicating the simulation's current progress"""
        return self._status

    @status.setter
    def status(self, value: str):
        self._status = value

    @property
    def files(self):
        """Set of file paths for files that will be created for this simulation"""
        return self._files

    @files.setter
    def files(self, value: set[str]):
        self._files = value

    @property
    def results(self):
        """Path to file containing analysed simulation results"""
        return self._results

    @results.setter
    def results(self, value: str):
        self._results = value

    async def stopTasks(self):
        """Stop any currently running tasks for this simulation"""

        for task in self.tasks:
            # Naming tasks for logging would require Python 3.12
            task.cancel()

        # Wait for all tasks to finish cancelling
        if self.tasks:
            await asyncio.gather(*self.tasks, return_exceptions=True)


activeSimulations: dict[str, SimData] = dict()


def clearFiles(files: set[str]):
    """
    Function to remove files generated by a simulation run after it is complete

    Parameters:
        files (set of str): A list of paths to files that must be removed.
    """
    # TODO: Add short delay if necessary for file downloads
    # TODO: Make sure files are deleted some time after a websocket breaks
    print("[clearFiles] Deleting the following files for cleanup purposes:")
    for f in files:
        print("   ", f, end="")
        try:
            os.remove(f)
            print()
        except FileNotFoundError:
            # Note files that already didn't exist
            print(" (not found)")


async def updateStatus(sim: SimData, state: str):
    """
    Simple async function to update the returned status of a server operation.

    Parameters:
        sim (SimData): The object containing the data used for this simulation.

        state (str): The state to set the task to.
    """
    # TODO: If other tasks don't use SimData modify the parameters here
    # TODO: Include time taken?
    sim.status = state

    # Broadcast to connected WebSockets
    message = {"status": state}
    for websocket in sim.websockets:
        try:
            await websocket.send_json(message)
            functionLog.info(f"Status for {sim.simulationID} updated to {message}\n")
        except Exception as e:
            functionLog.error(
                f"""
Status for {sim.simulationID} wasn't updated to {message} due to the following error:
{e}\n
                """
            )
            pass  # Ignore disconnected clients


def displayTime(startTime: datetime) -> str:
    """
    Calculates the time since a given point and displays it in mm:ss format

    Parameters:
        startTime (datetime): The point in time to measure from.

    Returns:
        str: The time between startTime and now, as a string in mm:ss format.
    """
    endTime = datetime.now()
    totalTime = endTime - startTime
    seconds = str(totalTime.seconds % 60).zfill(2)
    return f"{totalTime.seconds // 60}:{seconds}"


def generateToolboxConfig(
    sim: SimData, fileID: Optional[str], joint: Optional[str]
) -> str:
    """
    Function to generate the required toolbox config file for a simulation experiment

    Parameters:
        sim (SimData): The object containing the data used for this simulation.

        fileID (str): The numeric identifier for the files generated for this
            simulation, stored as a string.

        joint (str): A string used to label files generated by the simulation.

    Returns:
        str: The file path for the newly created configuration file.
    """
    toolboxConfigSettings = {
        "simulator_executable": "src/simulator/build/src/simulator",
        "baseline_file": "conf/simulation.baseline.json",
        "middle_joint": joint,
        "set_id_joint": "-",
        "event_suffix": ".sqlite",
        "input_directory": "results/",
        "output_directory": "post-analysis",
        "communities": [
            {"name": "newcastle", "path": "communities/newcastle2011"},
            {"name": "cairns", "path": "communities/cairns2011"},
            {"name": "integration", "path": "integration/community"},
        ],
    }

    # Log filename preemptively in case of cancellation
    toolboxConfigPath = f"tempFiles/toolbox_config_{fileID}.json"
    sim.files.add(toolboxConfigPath)
    print(
        (
            "[generateToolboxConfig] Generating toolbox "
            f"configuration file {toolboxConfigPath}"
        )
    )
    with open(toolboxConfigPath, "w") as file:
        json.dump(toolboxConfigSettings, file, indent=2)
    return toolboxConfigPath


async def runSimulation(
    sim: SimData,
    fileID: Optional[str],
    configData: modelGuideFile,
    toolboxPath: str,
):
    """
    Function to run a simulation experiment using the given config files

    Parameters:
        sim (SimData): The object containing the data used for this simulation.

        fileID (str): The numeric identifier for the files generated for this
            simulation, stored as a string.

        configData (modelGuideFile): The parameters and other settings that
            will define the simulation experiment.

        toolboxPath (str): The path to the file containing settings for the
            toolbox commands.
    """
    # from commands.Run.RunCommand import RunCommand
    from logger import LogLevel
    from ToolboxConfiguration import ToolboxConfiguration

    from serverFiles.toolboxOverrides import RunCommand

    runStartTime = datetime.now()
    toolboxConfig = ToolboxConfiguration(toolboxPath)

    guidePath = f"tempFiles/flusim-{fileID}.guide.json"

    # Get list of sim files so they can be deleted once the
    # simulation and analysis are complete
    simFiles = {
        os.path.join(
            simLocation,
            "results",
            (
                (
                    f"{configData.community_used[0]}{configData.middle_joint}"
                    f"{configData.simulation_sets[0].version}-{i:02}.sqlite"
                )
            ),
        )
        for i in range(len(configData.simulation_sets[0].simulations))
    }

    # Log files preemptively in case of cancellation
    sim.files |= simFiles | {guidePath}

    with open(guidePath, "w") as file:
        file.write(configData.model_dump_json(indent=2, exclude_unset=True))

    # Run the simulation
    await RunCommand(sim=sim).run_command(
        Namespace(guide=guidePath, log_level=LogLevel.DEBUG), toolboxConfig
    )
    print(
        "[runSimulation] Finished running the simulation experiment "
        f"in {displayTime(runStartTime)}\n"
    )


def epidemic(
    sim: SimData,
    fileID: Optional[str],
    communityName: str,
    joint: Optional[str],
    summaryStat=None,
    cumulative=False,
    byAge=False,
    toolboxPath: Optional[str] = None,
) -> list[str]:
    """
    Wrapper to run the epidemic toolbox command on a given simulation output,
    generating epidemic curves in CSV format.

    Parameters:
        sim (SimData): The object containing the data used for this simulation.

        fileID (str): The numeric identifier for the files generated for this
            simulation, stored as a string.

        communityName (str): The name of the community being simulated (e.g. Newcastle).

        joint (str): A string used to label files generated by the simulation.

        summaryStat (AnalysisStat, optional): Which summary statistic to use when
            generating the analysis data. Defaults to Median; None is converted
            to Median for import formatting purposes

        cumulative (bool): Set to True if you want to generate cumulative
            infections over time instead of daily infections.

        byAge (bool): Set to True if you want to generate separate epidemic
            curves for each age group.

        toolboxPath (str, optional): The path to the file containing settings
            for the toolbox commands.

    Returns:
        list of str: The name of the CSV files containing the generated
            epidemic curve(s), wrapped in a list to avoid issues when
            listing the required files.
    """
    from analysis.AnalysisStat import AnalysisStat
    from commands.epidemic import EpidemicCurveCommand
    from logger import LogLevel
    from ToolboxConfiguration import ToolboxConfiguration

    epidemicStartTime = datetime.now()
    if summaryStat is None:
        summaryStat = AnalysisStat.MEDIAN
    validPath = (
        toolboxPath if toolboxPath else f"tempFiles/toolbox_config_{fileID}.json"
    )
    toolboxConfig = ToolboxConfiguration(validPath)

    # Log files preemptively in case of cancellation
    fileStem = str(
        f"{communityName}{joint}{fileID}-epidemic-"
        f"{'cumulative-' if cumulative else ''}{summaryStat}",
    )
    oldFilename = os.path.join(simLocation, "post-analysis", f"{fileStem}.csv")
    newFilename = os.path.join(
        simLocation,
        "post-analysis",
        f"{fileStem}{'-by_age' if byAge else '-all_ages'}.csv",
    )
    sim.files |= {oldFilename, newFilename}

    # Run epidemic analysis
    # TODO: Integrate other options as params if needed by the dashboard
    epidemicArgs = Namespace(
        community=[communityName],
        set=[fileID],
        calculate_stat=summaryStat,
        cumulative_sum=cumulative,
        by_age=byAge,
        moving_average_window=7,
        scale=1,
        by_strain=False,
        age_adjusted=None,
        split_output=False,
        filenames=[],
        log_level=LogLevel.DEBUG,
    )
    print(
        "[epidemic] Running 'epidemic' analysis for "
        f"set {fileID} on community {communityName}"
    )
    print(
        f"Options: [{summaryStat}]",
        "[cumulative]" if cumulative else "[individual]",
        "[age-separated]" if byAge else "[age-combined]",
    )
    # TODO: See if EpidemicCurveCommand can be modified/overloaded to
    # call updateStatus after each simulation in the set
    EpidemicCurveCommand().run_command(epidemicArgs, toolboxConfig)

    # Rename file to account for all options and avoid overwriting previous data
    # TODO: Update new filename if more options are configurable
    os.rename(oldFilename, newFilename)
    orderedEpidemic = (
        pd.read_csv(newFilename, header=0).sort_index(axis=1).set_index("day")
    )
    if cumulative:
        orderedEpidemic = orderedEpidemic.ffill()
    orderedEpidemic.to_csv(newFilename, na_rep="0.0")
    print(
        "[epidemic] Finished running epidemic analysis "
        f"in {displayTime(epidemicStartTime)}\n"
    )
    return [newFilename]


# Function for asir toolbox function
def asir(
    sim: SimData,
    fileID: Optional[str],
    communityName: str,
    joint: Optional[str],
    summaryStat=None,
    getProportion=False,
    onlyIndigenous=False,
    onlyPregnant=False,
    onlyVaccinated=False,
    toolboxPath: Optional[str] = None,
) -> list[str]:
    """
    Wrapper to run the asir toolbox command on a given simulation output,
    generating age-separated infection rates in CSV format.

    Parameters:
        sim (SimData): The object containing the data used for this simulation.

        fileID (str): The numeric identifier for the files generated for this
            simulation, stored as a string.

        communityName (str): The name of the community being simulated (e.g. Newcastle).

        joint (str): A string used to label files generated by the simulation.

        summaryStat (AnalysisStat, optional): Which summary statistic to use when
            generating the analysis data. Defaults to Median; None is converted
            to Median for import formatting purposes

        getProportion (bool): Set to True if you want to generate infection
            rates as proportions of the population rather than exact values.

        onlyIndigenous (bool): Set to True if you want to generate rates for
            indigenous people specifically.

        onlyPregnant (bool): Set to True if you want to generate rates for
            pregnant people specifically.

        onlyVaccinated (bool): Set to True if you want to generate rates for
            vaccinated people specifically.

        toolboxPath (str, optional): The path to the file containing settings
            for the toolbox commands.

    Returns:
        list of str: The name of the CSV file containing the generated rates,
            wrapped in a list to avoid issues when listing the required files.
    """
    from analysis.AnalysisStat import AnalysisStat
    from commands.ASIRAnalysis import AsirCommand
    from logger import LogLevel
    from ToolboxConfiguration import ToolboxConfiguration

    asirStartTime = datetime.now()
    if summaryStat is None:
        summaryStat = AnalysisStat.MEDIAN
    validPath = (
        toolboxPath if toolboxPath else f"tempFiles/toolbox_config_{fileID}.json"
    )
    toolboxConfig = ToolboxConfiguration(validPath)

    # Log files preemptively in case of cancellation
    fileStem = f"{communityName}{joint}{fileID}-asir-{summaryStat}"
    oldFilename = os.path.join(simLocation, "post-analysis", f"{fileStem}.csv")
    newFilename = os.path.join(
        simLocation,
        "post-analysis",
        f"{fileStem}{'-proportion' if getProportion else '-discrete'}"
        f"{'-indigenousOnly' if onlyIndigenous else '-allDemographics'}"
        f"{'-pregnantOnly' if onlyPregnant else '-allPregnancy'}"
        f"{'-vaccinatedOnly' if onlyVaccinated else '-allVaccination'}.csv",
    )
    sim.files |= {oldFilename, newFilename}

    # Run epidemic analysis
    asirArgs = Namespace(
        community=[communityName],
        set=[fileID],
        calculate_stat=summaryStat,
        proportion=getProportion,
        indigenous=onlyIndigenous,
        pregnant=onlyPregnant,
        vaccinated=onlyVaccinated,
        filenames=[],
        log_level=LogLevel.DEBUG,
    )
    print(
        f"[asir] Running 'asir' analysis for set {fileID} on community {communityName}"
    )
    print(
        f"Options: [{summaryStat}]",
        "[proportionate]" if getProportion else "[discrete]",
        "[indigenous only]" if onlyIndigenous else "[all demographics]",
        "[pregnant only]" if onlyPregnant else "[all pregnant status]",
        "[vaccinated only]" if onlyVaccinated else "[all vaccine status]",
    )
    AsirCommand().run_command(asirArgs, toolboxConfig)

    # Rename file to account for all options and avoid overwriting previous data
    # TODO: Just modify the toolbox instead of doing this workaround
    os.rename(oldFilename, newFilename)

    # Order the scenarios correctly
    orderedAsir = pd.read_csv(newFilename, header=0, index_col=0).sort_index()
    orderedAsir.to_csv(newFilename, na_rep="0.0")

    print(f"[asir] Finished running asir analysis in {displayTime(asirStartTime)}\n")
    return [newFilename]
