# Flusim Web Interface Application
# Developed by Reilly Evans
# Functions for running the Flusim simulation

# Note that this file assumes it's just outside the smrg-flusim folder

# Imports
import json
import logging
import os
import sys
from argparse import Namespace
from datetime import datetime
from typing import Optional

import pandas as pd

from serverFiles.ModelSchema import modelGuideFile

# Change this if file location relative to Flusim changes
simLocation = ""

# Ensure Flusim imports work properly when called outside of toolbox
sys.path.append(os.path.join(os.getcwd(), simLocation, "src/toolbox"))

# Logging
functionLog = logging.getLogger(__name__)


def displayTime(startTime: datetime) -> str:
    """
    Calculates the time since a given point and displays it in mm:ss format

    Parameters:
        startTime (datetime): The point in time to measure from.

    Returns:
        str: The time between startTime and now, as a string in mm:ss format.
    """
    endTime = datetime.now()
    totalTime = endTime - startTime
    seconds = str(totalTime.seconds % 60).zfill(2)
    return f"{totalTime.seconds // 60}:{seconds}"


def generateToolboxConfig(id: Optional[str], joint: Optional[str]) -> str:
    """
    Function to generate the required toolbox config file for a simulation experiment

    Parameters:
        id (str): The numeric identifier for the simulation, stored as a string.

        joint (str): A string used to label files generated by the simulation.

    Returns:
        str: The file path for the newly created configuration file.
    """
    toolboxConfigSettings = {
        "simulator_executable": "src/simulator/build/src/simulator",
        "baseline_file": "conf/simulation.baseline.json",
        "middle_joint": joint,
        "set_id_joint": "-",
        "event_suffix": ".sqlite",
        "input_directory": "results/",
        "output_directory": "post-analysis",
        "communities": [
            {"name": "newcastle", "path": "communities/newcastle2011"},
            {"name": "cairns", "path": "communities/cairns2011"},
            {"name": "integration", "path": "integration/community"},
        ],
    }
    toolboxConfigPath = f"tempFiles/toolbox_config_{id}.json"
    print(
        (
            "[generateToolboxConfig] Generating toolbox "
            f"configuration file {toolboxConfigPath}"
        )
    )
    with open(toolboxConfigPath, "w") as file:
        json.dump(toolboxConfigSettings, file, indent=2)
    return toolboxConfigPath


def runSimulation(configData: modelGuideFile, toolboxPath: str) -> set[str]:
    """
    Function to run a simulation experiment using the given config files

    Parameters:
        configData (modelGuideFile): The parameters and other settings that
            will define the simulation experiment.

        toolboxPath (str): The path to the file containing settings for the
            toolbox commands.

    Returns:
        set of str: A list of file paths for each file created over the
            course of running the simulation.
    """
    from commands.Run.RunCommand import RunCommand
    from logger import LogLevel
    from ToolboxConfiguration import ToolboxConfiguration

    runStartTime = datetime.now()
    toolboxConfig = ToolboxConfiguration(toolboxPath)

    # Save guide file to JSON
    sessionID = configData.description
    guidePath = f"tempFiles/flusim-{sessionID}.guide.json"
    with open(guidePath, "w") as file:
        file.write(configData.model_dump_json(indent=2, exclude_unset=True))

    # Run the simulation
    RunCommand().run_command(
        Namespace(guide=guidePath, log_level=LogLevel.DEBUG), toolboxConfig
    )

    # Get list of sim files so they can be deleted once the
    # simulation and analysis are complete
    simFiles = {
        os.path.join(
            simLocation,
            "results",
            (
                (
                    f"{configData.community_used[0]}{configData.middle_joint}"
                    f"{configData.simulation_sets[0].version}-0{i}.sqlite"
                )
            ),
        )
        for i in range(len(configData.simulation_sets[0].simulations))
    }

    # Return required files so they can be deleted later
    print(
        "[runSimulation] Finished running the simulation experiment "
        f"in {displayTime(runStartTime)}\n"
    )
    return simFiles | {guidePath}


def epidemic(
    communityName: str,
    joint: Optional[str],
    id: Optional[str],
    summaryStat=None,
    cumulative=False,
    byAge=False,
    toolboxPath: Optional[str] = None,
) -> list[str]:
    """
    Wrapper to run the epidemic toolbox command on a given simulation output,
    generating epidemic curves in CSV format.

    Parameters:
        communityName (str): The name of the community being simulated (e.g. Newcastle).

        joint (str): A string used to label files generated by the simulation.

        id (str): The numeric identifier for the simulation, stored as a string.

        summaryStat (AnalysisStat, optional): Which summary statistic to use when
            generating the analysis data. Defaults to Median; None is converted
            to Median for import formatting purposes

        cumulative (bool): Set to True if you want to generate cumulative
            infections over time instead of daily infections.

        byAge (bool): Set to True if you want to generate separate epidemic
            curves for each age group.

        toolboxPath (str, optional): The path to the file containing settings
            for the toolbox commands.

    Returns:
        list of str: The name of the CSV files containing the generated
            epidemic curve(s), wrapped in a list to avoid issues when
            listing the required files.
    """
    from analysis.AnalysisStat import AnalysisStat
    from commands.epidemic import EpidemicCurveCommand
    from logger import LogLevel
    from ToolboxConfiguration import ToolboxConfiguration

    epidemicStartTime = datetime.now()
    if summaryStat is None:
        summaryStat = AnalysisStat.MEDIAN
    validPath = toolboxPath if toolboxPath else f"tempFiles/toolbox_config_{id}.json"
    toolboxConfig = ToolboxConfiguration(validPath)

    # Run epidemic analysis
    # TODO: Integrate other options as params if needed by the dashboard
    epidemicArgs = Namespace(
        community=[communityName],
        set=[id],
        calculate_stat=summaryStat,
        cumulative_sum=cumulative,
        by_age=byAge,
        moving_average_window=7,
        scale=1,
        by_strain=False,
        age_adjusted=None,
        split_output=False,
        filenames=[],
        log_level=LogLevel.DEBUG,
    )
    print(
        "[epidemic] Running 'epidemic' analysis for "
        f"set {id} on community {communityName}"
    )
    print(
        f"Options: [{summaryStat}]",
        "[cumulative]" if cumulative else "[individual]",
        "[age-separated]" if byAge else "[age-combined]",
    )
    # TODO: See if EpidemicCurveCommand can be modified/overloaded to
    # call updateStatus after each simulation in the set
    EpidemicCurveCommand().run_command(epidemicArgs, toolboxConfig)

    # Rename file to account for all options and avoid overwriting previous data
    # TODO: Update new filename if more options are configurable
    fileStem = str(
        f"{communityName}{joint}{id}-epidemic-"
        f"{'cumulative-' if cumulative else ''}{summaryStat}",
    )
    oldFilename = os.path.join(simLocation, "post-analysis", f"{fileStem}.csv")
    newFilename = os.path.join(
        simLocation,
        "post-analysis",
        f"{fileStem}{'-by_age' if byAge else '-all_ages'}.csv",
    )
    os.rename(oldFilename, newFilename)
    orderedEpidemic = pd.read_csv(newFilename, header=0).sort_index(axis=1)
    orderedEpidemic.set_index("day").to_csv(newFilename, na_rep="0.0")
    print(
        "[epidemic] Finished running epidemic analysis "
        f"in {displayTime(epidemicStartTime)}\n"
    )
    return [newFilename]


# Function for asir toolbox function
def asir(
    communityName: str,
    joint: Optional[str],
    id: Optional[str],
    summaryStat=None,
    getProportion=False,
    onlyIndigenous=False,
    onlyPregnant=False,
    onlyVaccinated=False,
    toolboxPath: Optional[str] = None,
) -> list[str]:
    """
    Wrapper to run the asir toolbox command on a given simulation output,
    generating age-separated infection rates in CSV format.

    Parameters:
        communityName (str): The name of the community being simulated (e.g. Newcastle).

        joint (str): A string used to label files generated by the simulation.

        id (str): The numeric identifier for the simulation, stored as a string.

        summaryStat (AnalysisStat, optional): Which summary statistic to use when
            generating the analysis data. Defaults to Median; None is converted
            to Median for import formatting purposes

        getProportion (bool): Set to True if you want to generate infection
            rates as proportions of the population rather than exact values.

        onlyIndigenous (bool): Set to True if you want to generate rates for
            indigenous people specifically.

        onlyPregnant (bool): Set to True if you want to generate rates for
            pregnant people specifically.

        onlyVaccinated (bool): Set to True if you want to generate rates for
            vaccinated people specifically.

        toolboxPath (str, optional): The path to the file containing settings
            for the toolbox commands.

    Returns:
        list of str: The name of the CSV file containing the generated rates,
            wrapped in a list to avoid issues when listing the required files.
    """
    from analysis.AnalysisStat import AnalysisStat
    from commands.ASIRAnalysis import AsirCommand
    from logger import LogLevel
    from ToolboxConfiguration import ToolboxConfiguration

    asirStartTime = datetime.now()
    if summaryStat is None:
        summaryStat = AnalysisStat.MEDIAN
    validPath = toolboxPath if toolboxPath else f"tempFiles/toolbox_config_{id}.json"
    toolboxConfig = ToolboxConfiguration(validPath)

    # Run epidemic analysis
    asirArgs = Namespace(
        community=[communityName],
        set=[id],
        calculate_stat=summaryStat,
        proportion=getProportion,
        indigenous=onlyIndigenous,
        pregnant=onlyPregnant,
        vaccinated=onlyVaccinated,
        filenames=[],
        log_level=LogLevel.DEBUG,
    )
    print(f"[asir] Running 'asir' analysis for set {id} on community {communityName}")
    print(
        f"Options: [{summaryStat}]",
        "[proportionate]" if getProportion else "[discrete]",
        "[indigenous only]" if onlyIndigenous else "[all demographics]",
        "[pregnant only]" if onlyPregnant else "[all pregnant status]",
        "[vaccinated only]" if onlyVaccinated else "[all vaccine status]",
    )
    AsirCommand().run_command(asirArgs, toolboxConfig)

    # Rename file to account for all options and avoid overwriting previous data
    # TODO: Just modify the toolbox instead of doing this workaround
    fileStem = f"{communityName}{joint}{id}-asir-{summaryStat}"
    oldFilename = os.path.join(simLocation, "post-analysis", f"{fileStem}.csv")
    newFilename = os.path.join(
        simLocation,
        "post-analysis",
        f"{fileStem}{'-proportion' if getProportion else '-discrete'}"
        f"{'-indigenousOnly' if onlyIndigenous else '-allDemographics'}"
        f"{'-pregnantOnly' if onlyPregnant else '-allPregnancy'}"
        f"{'-vaccinatedOnly' if onlyVaccinated else '-allVaccination'}.csv",
    )
    os.rename(oldFilename, newFilename)

    # Order the scenarios correctly
    orderedAsir = pd.read_csv(newFilename, header=0, index_col=0).sort_index()
    orderedAsir.to_csv(newFilename, na_rep="0.0")

    print(f"[asir] Finished running asir analysis in {displayTime(asirStartTime)}\n")
    return [newFilename]
