# Flusim Web Interface Application
# Developed by Reilly Evans
# Functions for running the Flusim simulation

# Note that this file assumes it's just outside the smrg-flusim folder

# Imports
import json
import logging
import os
import sys
from argparse import Namespace
from typing import Optional

import pandas as pd

from serverFiles.ModelSchema import modelGuideFile

# Change this if file location relative to Flusim changes
simLocation = ""

# Ensure Flusim imports work properly when called outside of toolbox
sys.path.append(os.path.join(os.getcwd(), simLocation, "src/toolbox"))

# Logging
functionLog = logging.getLogger(__name__)


def generateToolboxConfig(id: Optional[str], joint: Optional[str]) -> str:
    """
    Function to generate the required toolbox config file for a simulation experiment

    Parameters:
        id (str): The numeric identifier for the simulation, stored as a string.

        joint (str): A string used to label files generated by the simulation.

    Returns:
        str: The file path for the newly created configuration file.
    """
    toolboxConfigSettings = {
        "simulator_executable": "src/simulator/build/src/simulator",
        "baseline_file": "conf/simulation.baseline.json",
        "middle_joint": joint,
        "set_id_joint": "-",
        "event_suffix": ".sqlite",
        "input_directory": "results/",
        "output_directory": "post-analysis",
        "communities": [
            {"name": "newcastle", "path": "communities/newcastle2011"},
            {"name": "cairns", "path": "communities/cairns2011"},
            {"name": "integration", "path": "integration/community"},
        ],
    }
    toolboxConfigPath = f"serverFiles/toolbox_config_{id}.json"
    print(
        (
            "[generateToolboxConfig] Generating toolbox "
            f"configuration file {toolboxConfigPath}"
        )
    )
    with open(toolboxConfigPath, "w") as file:
        json.dump(toolboxConfigSettings, file, indent=2)
    return toolboxConfigPath


def runSimulation(configData: modelGuideFile, toolboxPath: str) -> list[str]:
    """
    Function to run a simulation experiment using the given config files

    Parameters:
        configData (modelGuideFile): The parameters and other settings that
            will define the simulation experiment.

        toolboxPath (str): The path to the file containing settings for the
            toolbox commands.

    Returns:
        list: A list of file paths for each file created over the course of
            running the simulation.
    """
    from commands.Run.RunCommand import RunCommand
    from logger import LogLevel
    from ToolboxConfiguration import ToolboxConfiguration

    # Get toolbox config
    toolboxConfig = ToolboxConfiguration(toolboxPath)

    # Save guide file to JSON
    sessionID = configData.description
    guidePath = f"serverFiles/flusim-{sessionID}.guide.json"
    with open(guidePath, "w") as file:
        file.write(configData.model_dump_json(indent=2, exclude_unset=True))

    # Run the simulation
    RunCommand().run_command(
        Namespace(guide=guidePath, log_level=LogLevel.DEBUG), toolboxConfig
    )

    # Get list of sim files so they can be deleted once the
    # simulation and analysis are complete
    simFiles = [
        os.path.join(
            simLocation,
            "results",
            (
                (
                    f"{configData.community_used[0]}{configData.middle_joint}"
                    f"{configData.simulation_sets[0].version}-0{i}.sqlite"
                )
            ),
        )
        for i in range(len(configData.simulation_sets[0].simulations))
    ]

    # Return required files so they can be deleted later
    return simFiles + [guidePath]


def epidemic(
    communityName: str,
    joint: Optional[str],
    id: Optional[str],
    summaryStat=None,
    cumulative=False,
    byAge=False,
    toolboxPath: Optional[str] = None,
) -> str:
    """
    Wrapper to run the epidemic toolbox command on a given simulation output,
    generating epidemic curves in CSV format.

    Parameters:
        communityName (str): The name of the community being simulated (e.g. Newcastle).

        joint (str): A string used to label files generated by the simulation.

        id (str): The numeric identifier for the simulation, stored as a string.

        summaryStat (AnalysisStat, optional): Which summary statistic to use when
            generating the analysis data. Defaults to Median; None is converted
            to Median for import formatting purposes

        cumulative (bool): Set to True if you want to generate cumulative
            infections over time instead of daily infections.

        byAge (bool): Set to True if you want to generate separate epidemic
            curves for each age group.

        toolboxPath (str, optional): The path to the file containing settings
            for the toolbox commands.

    Returns:
        str: The name of the CSV file containing the generated epidemic curve(s).
    """
    from analysis.AnalysisStat import AnalysisStat
    from commands.epidemic import EpidemicCurveCommand
    from logger import LogLevel
    from ToolboxConfiguration import ToolboxConfiguration

    # Get toolbox config
    if summaryStat is None:
        summaryStat = AnalysisStat.MEDIAN
    validPath = toolboxPath if toolboxPath else f"serverFiles/toolbox_config_{id}.json"
    toolboxConfig = ToolboxConfiguration(validPath)

    # Run epidemic analysis
    epidemicArgs = Namespace(
        community=[communityName],
        set=[id],
        calculate_stat=summaryStat,
        cumulative_sum=cumulative,
        by_age=byAge,
        moving_average_window=7,
        scale=1,
        by_strain=False,
        age_adjusted=None,
        split_output=False,
        filenames=[],
        log_level=LogLevel.DEBUG,
    )
    print(
        f'[epidemic] Running "epidemic" analysis for set {id} [{summaryStat}]',
        "[cumulative]" if cumulative else "[individual]",
        "[age-separated]" if byAge else "[age-combined]",
    )
    EpidemicCurveCommand().run_command(epidemicArgs, toolboxConfig)

    # Return the name of the newly processed file
    filename = os.path.join(
        simLocation,
        "post-analysis",
        (
            (
                f"{communityName}{joint}{id}-epidemic-"
                f"{'cumulative-' if cumulative else ''}{summaryStat}.csv"
            )
        ),
    )

    orderedEpidemic = pd.read_csv(filename, header=0).sort_index(axis=1)
    orderedEpidemic.set_index("day").to_csv(filename, na_rep="0.0")
    return filename


# Function for asir toolbox function
def asir(
    communityName: str,
    joint: Optional[str],
    id: Optional[str],
    summaryStat=None,
    getProportion=False,
    onlyIndigenous=False,
    onlyPregnant=False,
    onlyVaccinated=False,
    toolboxPath: Optional[str] = None,
) -> str:
    """
    Wrapper to run the asir toolbox command on a given simulation output,
    generating age-separated infection rates in CSV format.

    Parameters:
        communityName (str): The name of the community being simulated (e.g. Newcastle).

        joint (str): A string used to label files generated by the simulation.

        id (str): The numeric identifier for the simulation, stored as a string.

        summaryStat (AnalysisStat, optional): Which summary statistic to use when
            generating the analysis data. Defaults to Median; None is converted
            to Median for import formatting purposes

        getProportion (bool): Set to True if you want to generate infection
            rates as proportions of the population rather than exact values.

        onlyIndigenous (bool): Set to True if you want to generate rates for
            indigenous people specifically.

        onlyPregnant (bool): Set to True if you want to generate rates for
            pregnant people specifically.

        onlyVaccinated (bool): Set to True if you want to generate rates for
            vaccinated people specifically.

        toolboxPath (str, optional): The path to the file containing settings
            for the toolbox commands.

    Returns:
        str: The name of the CSV file containing the generated rates.
    """
    from analysis.AnalysisStat import AnalysisStat
    from commands.ASIRAnalysis import AsirCommand
    from logger import LogLevel
    from ToolboxConfiguration import ToolboxConfiguration

    # Get toolbox config
    if summaryStat is None:
        summaryStat = AnalysisStat.MEDIAN
    validPath = toolboxPath if toolboxPath else f"serverFiles/toolbox_config_{id}.json"
    toolboxConfig = ToolboxConfiguration(validPath)

    # Run epidemic analysis
    asirArgs = Namespace(
        community=[communityName],
        set=[id],
        calculate_stat=summaryStat,
        proportion=getProportion,
        indigenous=onlyIndigenous,
        pregnant=onlyPregnant,
        vaccinated=onlyVaccinated,
        filenames=[],
        log_level=LogLevel.DEBUG,
    )
    print(
        f'[asir] Running "asir" analysis for set {id} on community '
        f"{communityName} [{summaryStat}]",
        "[proportionate]" if getProportion else "[discrete]",
        "[indigenous only]" if onlyIndigenous else "[all demographics]",
        "[pregnant only]" if onlyIndigenous else "[all pregnant status]",
        "[vaccinated only]" if onlyIndigenous else "[all vaccine status]",
    )
    AsirCommand().run_command(asirArgs, toolboxConfig)
    filename = os.path.join(
        simLocation, f"post-analysis/{communityName}{joint}{id}-asir-{summaryStat}.csv"
    )

    # Order the scenarios correctly
    orderedAsir = pd.read_csv(filename, header=0, index_col=0).sort_index()
    orderedAsir.to_csv(filename, na_rep="0.0")

    # Return the name of the newly processed file
    return filename
